title: A Think a Week
email: athinkaweek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   This blog is will serve as my ledger of my engagement with the task of active self improvment.  Updates Sundays, will you join me?
baseurl: "" #"zaowen" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  zaowen

# Build settings
markdown: kramdown
#input:  GFM
theme: minima
permalink: pretty
plugins:
  - jekyll-feed

